### ISSUE TITLE
The Kermits-126 Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by amita-roy** [rloterh/NYTPageClone#3]
Content aligned a bit left side of the screen
Before and after selector to create "Thanks for reading" style in the middle of the page
Editor picks sidebar alignment needs improvement
The caption with video and images have some extra space
2 Paragraphs missing after inflation graphic
Main text column getting thinner while resizing
Bicep2 telescope image should be responsive
Navbar needs little more height
Before Footer above new york times logo needs a double border

Looks Amazing but needs some finishing!

**Comment by rloterh** [comment]
Issues fixed
